os : linux

language: rust

sudo: required 
rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - test

before_install:
  # execute all of the commands which need to be executed 
  # before installing dependencies
  - sudo apt install libssl-dev 
  - sudo apt install pkg-config

install:
  # install all of the dependencies you need here
  - rustup update
  
before_script:
  # execute all of the commands which need to be executed 
  # before running actual tests
  - pwd

script:
  # execute all of the commands which 
  # should make the build pass or fail
  - cargo build 
  - cd target 
  - cd debug
  - sudo mv rust-wget /usr/bin/

